// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// Station represents a row from '[custom station]'.
type Station struct {
	LineCd      int    // line_cd
	LineName    string // line_name
	StationCd   int    // station_cd
	StationGCd  int    // station_g_cd
	StationName string // station_name
	Address     string // address
}

// StationsByStationCD runs a custom query, returning results as Station.
func StationsByStationCD(db XODB, stationCD string) ([]*Station, error) {
	var err error

	// sql query
	const sqlstr = `select l.line_cd, l.line_name, s.station_cd, station_g_cd, s.station_name, s.address ` +
		`from station s ` +
		`inner join line l on s.line_cd = l.line_cd ` +
		`where s.station_cd = $1 ` +
		`and s.e_status = 0`

	// run query
	XOLog(sqlstr, stationCD)
	q, err := db.Query(sqlstr, stationCD)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*Station{}
	for q.Next() {
		s := Station{}

		// scan
		err = q.Scan(&s.LineCd, &s.LineName, &s.StationCd, &s.StationGCd, &s.StationName, &s.Address)
		if err != nil {
			return nil, err
		}

		res = append(res, &s)
	}

	return res, nil
}
