// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// StationByCD represents a row from '[custom station_by_c_d]'.
type StationByCD struct {
	LineCd      int    // line_cd
	LineName    string // line_name
	StationCd   int    // station_cd
	StationGCd  int    // station_g_cd
	StationName string // station_name
	Address     string // address
}

// StationByCDsByStationCD runs a custom query, returning results as StationByCD.
func StationByCDsByStationCD(db XODB, stationCD int) ([]*StationByCD, error) {
	var err error

	// sql query
	const sqlstr = `select l.line_cd, l.line_name, s.station_cd, station_g_cd, s.station_name, s.address ` +
		`from station s ` +
		`inner join line l on s.line_cd = l.line_cd ` +
		`where s.station_cd = $1 ` +
		`and s.e_status = 0`

	// run query
	XOLog(sqlstr, stationCD)
	q, err := db.Query(sqlstr, stationCD)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*StationByCD{}
	for q.Next() {
		sbcd := StationByCD{}

		// scan
		err = q.Scan(&sbcd.LineCd, &sbcd.LineName, &sbcd.StationCd, &sbcd.StationGCd, &sbcd.StationName, &sbcd.Address)
		if err != nil {
			return nil, err
		}

		res = append(res, &sbcd)
	}

	return res, nil
}
