// Package models contains the types for schema 'public'.
package models

// Code generated by xo. DO NOT EDIT.

// StationByName represents a row from '[custom station_by_name]'.
type StationByName struct {
	LineCd      int    // line_cd
	LineName    string // line_name
	StationCd   int    // station_cd
	StationGCd  int    // station_g_cd
	StationName string // station_name
	Address     string // address
}

// StationByNamesByStationName runs a custom query, returning results as StationByName.
func StationByNamesByStationName(db XODB, stationName string) ([]*StationByName, error) {
	var err error

	// sql query
	const sqlstr = `select l.line_cd, l.line_name, s.station_cd, station_g_cd, s.station_name, s.address ` +
		`from station s ` +
		`inner join line l on s.line_cd = l.line_cd ` +
		`where s.station_name = $1 ` +
		`and s.e_status = 0`

	// run query
	XOLog(sqlstr, stationName)
	q, err := db.Query(sqlstr, stationName)
	if err != nil {
		return nil, err
	}
	defer q.Close()

	// load results
	res := []*StationByName{}
	for q.Next() {
		sbn := StationByName{}

		// scan
		err = q.Scan(&sbn.LineCd, &sbn.LineName, &sbn.StationCd, &sbn.StationGCd, &sbn.StationName, &sbn.Address)
		if err != nil {
			return nil, err
		}

		res = append(res, &sbn)
	}

	return res, nil
}
